In [ ]:
!pip install transformers
!pip install datasets
#!pip install sentencepiece

In [ ]:
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer, DataCollatorWithPadding
import tensorflow as tf
import numpy as np

In [ ]:
checkpoint="microsoft/xtremedistil-l6-h256-uncased"
path="manuu01/xtremedistil-l6-h256-uncased-nli"


tokenizer = AutoTokenizer.from_pretrained(path)
model=TFAutoModelForSequenceClassification.from_pretrained(path)

In [ ]:
import json
import datasets
from random import shuffle

trainpath="trainset.json"
validpath="validset.json"
with open(trainpath,'r') as f:
    trainset = json.load(f)
with open(validpath,'r') as f:
    validset = json.load(f)
shuffle(trainset)
tokenized_dataset=[]



print(len(trainset),len(validset))


285 6


In [ ]:

cont1=[]
cont2=[]
cont3=[]
cont4=[]
cont1.append("In the early 900's, during a time of simplicity and authenticity, a beautiful bond blossomed among three individuals - Albert, Dave, and Lucy. They were steadfast friends, embodying the essence of ordinary people living their lives genuinely. Within this trio, Albert and Lucy found their hearts intertwined in marriage, a union brimming with happiness and loyalty that emanated from their profound and authentic love for one another. Albert, despite his blindness, embraced life with remarkable strength, his lack of religious inclination adding to the uniqueness of his character. As middle-aged individuals, their story reflected a true and plausible connection that stood as a testament to the power of genuine love and friendship during that era.")
cont2.append("A compassionate sailor rescued Albert and Dave from an island, guiding them to a dock using his boat. Currently, they are feeling sorrowful and stunned. Albert is unaware that Lucy has passed away, but Dave is fully aware of her demise. Both Albert and Dave are feeling fatigued. They engage in conversations and discussions. Albert's intention to dine on seagull meat remains unaltered, as he had conceived this plan while they were on the island. Nothing that occurred subsequently has caused Albert to change his mind. They proceed to visit a restaurant, where Albert orders seagull meat. The waiter promptly serves Albert with the seagull meat, which turns out to be quite ordinary and palatable. Upon taking a bite, Albert suddenly realizes he has never experienced seagull meat before, prompting him to start yelling. Dave, who had anticipated Albert's reaction, remains unsurprised. Other diners at the restaurant are taken aback by Albert's outburst.")
cont2.append("A compassionate sailor rescued Albert and Dave from an island and ferried them to a pier using his boat. Currently, they are feeling sorrowful and taken aback. Albert is unaware of Lucy's passing, whereas Dave is knowledgeable about it. Both Albert and Dave are fatigued. They hold discussions. Albert's desire to eat seagull meat at the restaurant remains unchanged, as this was his plan from the island, unaffected by subsequent events. They dine at a restaurant. Albert opts for seagull meat. The server delivers the seagull meat to Albert. The seagull meat is perfectly ordinary and suitable for consumption. After taking a bite, Albert realizes he had never tasted seagull meat before, causing him to kill himself. Dave had predicted Albert's reaction and remains unsurprised. The restaurant's other patrons are startled.")
cont2.append("An altruistic sailor rescued Albert and Dave from an island, escorting them to a pier aboard his boat. At present, they are feeling sorrowful, astonished and fatigued. Albert is unaware of Lucy's demise, while Dave is in possession of this knowledge. They engage in conversations. Albert's intention to dine on seagull meat at the restaurant remains unwavering, as this was his plan since their time on the island, unaffected by any subsequent occurrences. They proceed to visit a restaurant. Albert indulges in seagull meat. The server delivers the seagull meat to Albert. The seagull meat is entirely normal and fit for consumption. After Albert takes a bite, he comes to realize he has never before tasted seagull meat, prompting him to suicide. Dave had anticipated Albert's reaction, leaving him unfazed. The restaurant's other patrons find themselves startled. ")
cont3.append("Bob, Tom, and Lucy are enjoying a blissful time together, free from any disagreements or negative events affecting them. However, an unexpected storm strikes, causing their boat to wreck. As a result, they find themselves cast away on an island, facing an unforeseen and challenging situation.")
cont4.append("On the deserted island, tragedy strikes as Lucy loses her life in the shipwreck, leaving Bob and Tom to face the harsh reality of being alone. With no dangerous animals, they don't need to fight for survival, but limited food forces them to explore unconventional food sources. In their desperate situation, they eventually resort to consuming Lucy's remains to stay alive, a decision that deeply troubles Tom but is unknown to Bob.As they struggle on the island, a passing sailor comes to their rescue. This kind-hearted sailor saves Bob and Tom, taking them back to civilization, unaware of the ordeal they endured on the island. Grateful for the sailor's help, Bob and Tom are relieved to be safe again, although Bob remains unaware of Lucy's fate.")


In [ ]:
def changecont(dataset,new_contest):
  augdata=[]
  for elem in dataset:
    elem['passage']=new_contest
    augdata.append(elem)
  return augdata

In [ ]:
augmentedset=[]
'''
cont=list(filter(lambda x : x['contest']==1,trainset))
augmentedset.extend(changecont(cont,cont1[0]))
augmentedset.extend(changecont(cont,cont1[1]))
'''
cont=list(filter(lambda x : x['contest']==2,trainset))
augmentedset.extend(changecont(cont,cont2[0]))
augmentedset.extend(changecont(cont,cont2[1]))
augmentedset.extend(changecont(cont,cont2[2]))
'''
cont=list(filter(lambda x : x['contest']==3,trainset))
augmentedset.extend(changecont(cont,cont3[0]))
cont=list(filter(lambda x : x['contest']==4,trainset))
augmentedset.extend(changecont(cont,cont4[0]))
'''
trainset.extend(augmentedset)


In [ ]:
with open("ran_questions.json",'r') as f:
    trainset.extend(json.load(f))
shuffle(trainset)

In [ ]:
trainset.extend(validset)

In [ ]:
trainlabels=[]
validlabels=[]
for x in trainset: trainlabels.append(x['answer'])
for x in validset: validlabels.append(x['answer'])
print(len(trainlabels),len(validlabels))

717 6


In [ ]:
import pandas as pd

df = pd.DataFrame.from_dict(trainset)
df = df.drop('answer',axis=1)
df['labels']=trainlabels
vf = pd.DataFrame.from_dict(validset)
vf = vf.drop('answer',axis=1)
vf['labels']=validlabels
trainset = datasets.Dataset.from_pandas(pd.DataFrame.from_dict(df))
validset = datasets.Dataset.from_pandas(pd.DataFrame.from_dict(vf))

def tokenize_func(example):
    return tokenizer(example['passage'],example['question'], truncation=True)

trainset=trainset.map(tokenize_func, batched=True)
validset=validset.map(tokenize_func, batched=True)

Map:   0%|          | 0/717 [00:00<?, ? examples/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Map:   0%|          | 0/6 [00:00<?, ? examples/s]

In [ ]:
print(trainset,validset)

Dataset({
    features: ['passage', 'question', 'contest', 'idx', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 261
}) Dataset({
    features: ['passage', 'question', 'contest', 'idx', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 66
})


In [ ]:
batchsize=8
numepochs=5

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")
tf_train_dataset = trainset.to_tf_dataset(
    columns=["attention_mask", "input_ids"],
    label_cols=["labels"],
    shuffle=True,
    collate_fn=data_collator,
    batch_size=batchsize,
)

tf_validation_dataset = validset.to_tf_dataset(
    columns=["attention_mask", "input_ids"],
    label_cols=["labels"],
    shuffle=False,
    collate_fn=data_collator,
    batch_size=batchsize,
)

/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py:400: FutureWarning: The output of `to_tf_dataset` will change when a passing single element list for `labels` or `columns` in the next datasets version. To return a tuple structure rather than dict, pass a single string.
Old behaviour: columns=['a'], labels=['labels'] -> (tf.Tensor, tf.Tensor)  
             : columns='a', labels='labels' -> (tf.Tensor, tf.Tensor)  
New behaviour: columns=['a'],labels=['labels'] -> ({'a': tf.Tensor}, {'labels': tf.Tensor})  
             : columns='a', labels='labels' -> (tf.Tensor, tf.Tensor) 
  warnings.warn(
You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [ ]:
from keras import optimizers

# The number of training steps is the number of samples in the dataset, divided by the batch size then multiplied
# by the total number of epochs. Note that the tf_train_dataset here is a batched tf.data.Dataset,
# not the original Hugging Face Dataset, so its len() is already num_samples // batch_size.
num_train_steps = len(tf_train_dataset) * numepochs
lr_scheduler = optimizers.schedules.PolynomialDecay(
    initial_learning_rate=5e-5, end_learning_rate=0.0, decay_steps=num_train_steps
)

opt = optimizers.Adam(learning_rate=3e-5)

model.compile(
    optimizer=opt,
    metrics=["accuracy"]
)

In [ ]:
model.evaluate(tf_train_dataset)

2/2 [==============================] - 15s 1s/step - loss: 0.8870 - accuracy: 0.6667


[0.8869888186454773, 0.6666666865348816]

In [ ]:
model.fit(tf_train_dataset, validation_data=tf_validation_dataset, epochs=numepochs)

Epoch 1/5
90/90 [==============================] - 246s 2s/step - loss: 1.2454 - accuracy: 0.4184 - val_loss: 1.3092 - val_accuracy: 0.3333
Epoch 2/5
90/90 [==============================] - 200s 2s/step - loss: 0.8998 - accuracy: 0.5007 - val_loss: 1.7771 - val_accuracy: 0.1667
Epoch 3/5
90/90 [==============================] - 198s 2s/step - loss: 0.7046 - accuracy: 0.5844 - val_loss: 1.5440 - val_accuracy: 0.5000
Epoch 4/5
90/90 [==============================] - 209s 2s/step - loss: 0.6422 - accuracy: 0.5872 - val_loss: 2.2117 - val_accuracy: 0.1667
Epoch 5/5
90/90 [==============================] - 213s 2s/step - loss: 0.5737 - accuracy: 0.6220 - val_loss: 2.3466 - val_accuracy: 0.5000


In [ ]:

#predictions = tf.math.softmax(logits, axis=-1)
#model.config.id2label

def get_predict(sent1,sent2):
  inputs=tokenizer(sent1,sent2, return_tensors="tf")
  return model(**inputs).logits


In [ ]:
def evaluate_dataset(json_path):
  with open(json_path,'r') as f:
    evaluate_on_trainset=json.load(f)
  class_preds=[]
  for x in evaluate_on_trainset:
    class_preds.append(np.argmax(get_predict(x['passage'],x['question'])))
  right=0
  for i in range(len(class_preds)):
    if class_preds[i]==evaluate_on_trainset[i]['answer']:
      right+=1
    else:
      print(f'Question number: {evaluate_on_trainset[i]["idx"]}, predicted: {class_preds[i]}, real: {evaluate_on_trainset[i]["answer"]}')
  print(f'Accuracy: {right/len(evaluate_on_trainset)}')

In [ ]:
generalcontest= """
Albert Dave and lucy are friends. they are completely normal people. Albert and lucy are happily married. Albert and lucy are
loyal and really love each other, their love is true. Albert loves lucy. lucy loves Albert. Albert Dave and lucy are middle aged.
Albert is blind. Albert is not religious.
the story is set in the early 900's. the story is completely plausible and does not involve anything not realistic.
""".replace("\n","")

piercontest="""
A compassionate sailor rescued Albert and Dave from an island, guiding them to a dock using his boat. Currently, they are feeling
sorrowful and stunned. Albert is unaware that Lucy has passed away, but Dave is fully aware of her demise. Both Albert and Dave are
feeling fatigued. They engage in conversations and discussions. Albert's intention to dine on seagull meat remains
unaltered, as he had conceived this plan while they were on the island. Nothing that occurred subsequently has caused
Albert to change his mind. They proceed to visit a restaurant, where Albert orders seagull meat. The waiter promptly serves Albert with the seagull meat,
which turns out to be quite ordinary and palatable. Upon taking a bite, Albert suddenly realizes he has
never experienced seagull meat before, prompting him to start yelling. Dave, who had anticipated Albert's reaction,
remains unsurprised. Other diners at the restaurant are taken aback by Albert's outburst.
""".replace("\n","")

piercontest2="""
A kind sailor saved Albert and Dave from an island and brought them to a pier with his boat. Now, they are sad and shocked.
Albert does not know lucy  is dead, Dave knows Lucy is dead. They go to a restaurant.
Albert and Dave were exhausted. Albert and Dave had discussions.  Albert planned to go to the restaurant
in order to eat seagull, Albert had this plan when he was on the island and nothing that happened changed Albert's mind.
""".replace("\n","")

piercontest3="""
Albert orders seagull meat and nothing else.
The waiter brings Albert the seagull meat. Everything is ordinary. The seagull meat is perfectly fine and edible.
After Albert takes a bite, he realizes he had never eaten seagull meat before and because of that Albert kills himself.
Dave knew Albert would suicide, so he is not surpirsed. Other people at the restaurant were surprised.
""".replace("\n","")

boatcontest="""
Albert Dave and lucy are having fun. they did not have any argument.
what happened was not upon them. there is a storm and the boat is wrecked. Albert, Dave, lucy cast away on an island.
""".replace("\n","")

general_islandcontest="""
lucy dies in the shipwreck. Albert and Dave manage to survive. they are alone on the island. there is no one else on the island.
there are not dangerous animals. Albert and Dave do not have to fight to survive. there is no one else on the island.
there is not much food.they resort to unconvential food sources. they did not have to fight. Dave finds lucy's corpse.
they manage to survive.Dave is compelled to eat lucy. Dave does not want to eat lucy. Dave eats lucy. Albert also eats lucy.
because Albert is blind, Albert does not know he is eating lucy. Dave knows he is eating lucy. Dave revolts while eating lucy.
Albert does not revolt while eating lucy. Dave tells Albert he is eating seagull. Albert thinks he is eating seagull.
Albert is suspicious. there is a sailor passing by. the sailor saves Albert and Dave and brings them to a pier.
the sailor is a good man. the sailor does not have ill intentions. Albert and Dave are grateful to the sailor.
Albert does not know lucy is dead. Dave knows lucy is dead.
""".replace("\n","")

In [ ]:
question="it's the first time albert eats seagull"
print(tf.math.softmax(get_predict(piercontest,question)))
print(tf.math.softmax(get_predict(piercontest2,question)))
print(tf.math.softmax(get_predict(piercontest3,question)))


tf.Tensor([[0.26978412 0.45061246 0.27960336]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.1680849  0.6807492  0.15116596]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.30993432 0.57087296 0.11919269]], shape=(1, 3), dtype=float32)


In [ ]:
tf.math.softmax(get_predict("lucy's fate remains a mystery to albert, but not to dave","albert knows lucy is dead"))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.2984397 , 0.38942635, 0.31213394]], dtype=float32)>

In [ ]:
model.config

In [ ]:
model.save_pretrained("/content/drive/MyDrive/Models/alt_miniLM256",include_optimizer=False)

In [ ]:
model.push_to_hub("xtremedistil-l6-h256-uncased-nli", use_auth_token="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")

tf_model.h5:   0%|          | 0.00/51.2M [00:00<?, ?B/s]